name: Legendarys
version: '1.0'
main: org.tekkabyte.legendarys.LegendarysPlugin
api-version: '1.21'
softdepend: [ProtocolLib]
author: Tekkabyte
commands:
  legendary:
    description: Manage legendary tagging and templates
    usage: /legendary set <id> [--save] | /legendary save | /legendary delete <page> <slot> | /legendary replace <page> <slot> | /legendary give <page> <slot> [player]
    permission: legendarys.admin
  viewlegendaries:
    description: View legendary templates GUI
    usage: /viewlegendaries <page>
    permission: legendarys.admin

permissions:
  legendarys.admin:
    default: op